# Generated by Django 4.0.5 on 2022-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
