# Generated by Django 4.0.5 on 2022-06-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_delete_blog_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default', upload_to=''),
        ),
    ]
